# Generated by Django 5.1.2 on 2024-10-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='example',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
